Adds detection for yarn, and '--no-yarn' to suppress detection
microsoft/vscode-vsce pull request #492
Opened 2020-09-24 19:16 UTC by rbuckton

This adds automatic detection of `yarn` based on the presence of either a `yarn.lock` or `.yarnrc` file in the current directory. Passing `--yarn` or `--no-yarn` disables automatic detection.

Fixes #480

2020-09-24 19:21 UTC, rbuckton commented on src/package.ts
> +	await new Promise<void>((c, e) => {
In TypeScript 4.1, the value to `resolve()` is no longer optional unless a `Promise` is given the type `Promise<void>` (either explicitly or via a contextual type). Even though vsce currently uses TypeScript 3.4, I added this because it'll be an issue in the future (also, I am running VS Code Insiders with the latest TS 4.1 build and it showed up as a diagnostic).

2020-09-24 19:51 UTC, felipecrs approved these changes
LGTM

2020-09-24 20:06 UTC, rbuckton commented
This might need to be updated if #458 goes in, as this currently only looks for `yarn.lock` and `.yarnrc` in the current directory, but if you're publishing an from a package subdirectory in a yarn workspace, neither of those two files will be present since the current directory is not the workspace root.

2020-09-24 20:19 UTC, rbuckton commented
Build is failing before it starts due to the node version used to run the build:

```
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error husky@4.3.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

https://dev.azure.com/vscode/VSCE/_build/results?buildId=53730&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b&l=18

2020-09-24 20:21 UTC, rbuckton commented
@joaomoreno I bumped the node version in `azure-pipelines.yml` to get the build to pass. I can revert that if you still want to be sure it builds/tests on NodeJS 8, but I can't do much about husky 4.3.0 not supporting node 8.

2020-09-30 11:46 UTC, joaomoreno requested changes

2020-09-30 11:46 UTC, joaomoreno commented on src/package.ts
> +		if (fs.existsSync(path.join(cwd, file))) {
Using `sync` is out of question. We should rewrite this to be fully async.

2020-09-30 11:46 UTC, joaomoreno commented on src/package.ts
> +			console.log(`Detected presense of ${file}. Using 'yarn' instead of 'npm' (to override this pass '--no-yarn' on the command line).`);
We have a logging util in `util.ts`, let's use that instead.

2020-09-30 11:46 UTC, joaomoreno commented on src/npm.ts
> +	if (fs.existsSync(path.join(cwd, 'yarn.lock'))) {
We can't use sync because there are other operations which might run in the background, ie checking for updates.

This needs to stay as async, and `stat` should be used.

2020-09-30 11:47 UTC, joaomoreno commented on src/main.ts
> +		.option('--no-yarn', 'Use npm instead of yarn (default inferred from lack of yarn.lock or .yarnrc)')
Should this perhaps be `--npm`?

2020-09-30 21:55 UTC, rbuckton commented on src/main.ts
> +		.option('--no-yarn', 'Use npm instead of yarn (default inferred from lack of yarn.lock or .yarnrc)')
The arg parser you're using (commander), has specific handling for `--foo` and `--no-foo`: https://www.npmjs.com/package/commander#other-option-types-negatable-boolean-and-flagvalue. If you make the flag `--npm`, then you have to manually disambiguate and report errors for using `--npm --yarn`

2020-09-30 22:06 UTC, rbuckton commented on src/package.ts
> +		if (fs.existsSync(path.join(cwd, file))) {
That's a bit more complex because you can't use `await` in a parameter initializer, and the version of TypeScript you're using doesn't support `??`. I'll look into it though.

2020-10-01 08:37 UTC, joaomoreno commented on src/main.ts
> +		.option('--no-yarn', 'Use npm instead of yarn (default inferred from lack of yarn.lock or .yarnrc)')
Oh yeah, cool.

2020-10-01 10:17 UTC, joaomoreno commented on src/package.ts
> +	if (useYarn === undefined) useYarn = await detectYarn(cwd);
```suggestion
	if (useYarn === undefined) {
		useYarn = await detectYarn(cwd);
	}
```

2020-10-01 10:18 UTC, joaomoreno approved these changes
Thanks!

2020-10-01 10:19 UTC, merged