Ensure package.json is writable in *.vsix
microsoft/vscode-vsce pull request #508
Opened 2020-11-18 13:24 UTC by FabianHenneke

VSC requires the manifest file unpacked from the .vsix archive to be
marked as writable (see [1]). Since generating writable artifacts is
difficult in some build systems (such as Bazel), it would be helpful if
vsce itself could ensure that the file mode of the manifest is correct.

With this commit, the correct file mode on `package.json` is set
automatically by the packaging process via a new `Processor` and yazl's
`mode` argument.

[1]: https://github.com/microsoft/vscode/blob/88144f6d31718288c7a2c6fb741e0646d40804cf/src/vs/platform/extensionManagement/node/extensionsScanner.ts#L144

2020-11-19 15:45 UTC, joaomoreno requested changes
Makes sense. But why not simply implement `onFile` on the `ManifestProcessor` and change the file mode when the `package.json` file comes along? This would be a much smaller change.

2020-11-19 15:45 UTC, joaomoreno commented on src/package.ts
> +	explicitMode?: number;
Let's just call this `mode`.

2020-11-19 15:45 UTC, joaomoreno commented on src/package.ts
> +	explicitMode?: number;
Let's just call this `mode`.

2020-11-20 08:27 UTC, FabianHenneke commented
Thanks for the suggestion, I have made the required changes.

2020-11-20 08:47 UTC, joaomoreno commented on src/package.ts
> +		}
Would this work too?

```suggestion
		return { ...file, mode };
```

2020-11-20 09:05 UTC, FabianHenneke commented on src/package.ts
> +		}
It does, thanks!

2020-11-20 09:08 UTC, joaomoreno reviewed
Looking great! Wanna try adding a test for it? It should be relatively straightforward.

2020-11-20 10:54 UTC, FabianHenneke commented
I added a unit test for `MetadataProcessor`. Is that what you intended?

2020-11-20 10:54 UTC, merged

2020-11-20 10:54 UTC, joaomoreno commented
Great work, thanks! 🍻

2020-12-08 14:44 UTC, fmeum commented
Would it be possible to get an NPM release of 1.83.0?