feat: warn users about missing LICENSE
Microsoft/vscode-vsce pull request #628
Opened 2021-10-08 19:26 UTC by Andrewnt219

## Motivation

Fixes #603 

When the code fails to automatically detect a LICENSE file, it now warns the users if they want to continue.

## Test Plan

Run `vsce package` without a `LICENSE` should generate a warning message.
```bash
# No LICENSE. 
# No 'SEE LICENSE IN term.md'

PS C:\helloworld> vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> helloworld@0.0.1 vscode:prepublish
> npm run compile

> helloworld@0.0.1 compile
> tsc -p ./

 WARNING LICENSE.md or LICENSE.txt not found
Do you want to continue? [Y/N]

# No LICENSE. 
# Has 'SEE LICENSE IN term.md'

PS C:\helloworld> vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> helloworld@0.0.1 vscode:prepublish
> npm run compile

> helloworld@0.0.1 compile
> tsc -p ./

 WARNING  term.md not found
Do you want to continue? [Y/N]

# Has LICENSE. 
# Has 'SEE LICENSE IN term.md'

PS C:\helloworld> vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> helloworld@0.0.1 vscode:prepublish
> npm run compile

> helloworld@0.0.1 compile
> tsc -p ./

 WARNING  term.md not found
Do you want to continue? [Y/N]
```

2021-10-11 06:51 UTC, joaomoreno requested changes
>I have read through the README, but I don't know how I can set up dev environment to reporuce the case.

Yeah, the current steps seems to be broken. I've fixed those in `main`.

2021-10-11 06:51 UTC, joaomoreno commented on src/package.ts
> +			} else {
This will ask the user for every file vsce finds in disk, before it finds the license file. The right place to ask the user is in the `onEnd` method.

2021-10-11 06:51 UTC, joaomoreno commented on src/package.ts
> +				util.log.warn(`LICENSE file not found`);
The file can be named differently, please read the constructor of this class.

2021-10-11 06:51 UTC, joaomoreno commented on src/package.ts
> +				if (!/^y$/i.test(await util.read('Do you want to continue? [y/N] '))) {
We probably want the default to be `Y`.

2021-10-12 17:51 UTC, joaomoreno commented on src/package.ts
> +			this.expectedLicenseName = 'license';
```suggestion
			this.expectedLicenseName = 'LICENSE.md or LICENSE.txt';
```

2021-10-12 21:21 UTC, teamsedition commented
I am

2021-10-13 13:14 UTC, joaomoreno commented on src/package.ts
> +			if (!/^Y$/i.test(await util.read('Do you want to continue? [Y/N] '))) {
```suggestion
			if (!/^y$/i.test(await util.read('Do you want to continue? [Y/n] '))) {
```

2021-10-13 13:16 UTC, merged

2021-12-03 20:22 UTC, lnicola commented
I'm not sure how this is supposed to work, but if the license is already defined in `package.json`, the (previous) code still looked for a file on disk. Is that intentional?

2021-12-06 08:56 UTC, joaomoreno commented
@lnicola The SPDX string only changes the lice file name to look for. It will always look for a license file.