fix: ensure that we can define dependency argument in config
microsoft/vscode-vsce pull request #743
Opened 2022-06-17 08:11 UTC by ssbarnea

Fixes: #742

2022-06-17 09:00 UTC, ssbarnea commented
@joaomoreno If you can take a look at this it would be awesome, that is a real blocker for our switch from npm to yarn for building, as we cannot add custom command line arguments to vsce calls.

2022-06-17 14:04 UTC, joaomoreno requested changes

2022-06-17 14:04 UTC, joaomoreno commented on README.md
> +    "yarn": false
It is really necessary to change the docs for this?

2022-06-17 14:12 UTC, ssbarnea commented on README.md
> +    "yarn": false
I would that that is highly desirable. It took two people on our side to investigate/guess how arguments are translated to settings entries. In fact I would be happy to see full setting example with all supported settings.

Still, if you want this the docs change to be separated it would be fine, I can do it. I just explained why updating documented example is important. Also it would be ok to put default values there instead of custom ones, for example we could put "dependencies: null" which I guess is the correspondent of undefined.

Let me know in which direction to take it.

2022-06-17 19:19 UTC, joaomoreno commented on README.md
> +    "yarn": false
All good and your reasoning makes sense, thanks!

2022-06-17 19:19 UTC, joaomoreno approved these changes

2022-06-18 07:19 UTC, ssbarnea commented
Sadly I am unable to request the failed job rerun. I am sure it was a glitch and that has nothing to do with this PR.

2022-06-18 07:21 UTC, ssbarnea commented
Please approve GHA run.

2022-06-20 11:32 UTC, ssbarnea commented
Any chance to get this merged? Asking as I do not want to miss it from the next release. Thanks!

2022-06-21 13:36 UTC, merged