feat: add user-friendly info to --help
microsoft/vscode-vsce pull request #884
Opened 2023-08-01 19:57 UTC by bandantonio

Resolves #769 

## Description

This PR adds basic user-friendly message as a description, which is expected to appear at every command passed with the `--help` flag. The current `commander` version (6.1.0) doesn't support certain commands that help adding this message properly (like only for the 'root' help), as well as other commands that potentially can be helpful in optimizing the current code and removing the parts that `commander` has implemented under-the-hood (like showing suggestions on errors).
So I would highly suggest creating an issue to proceed with migration to version [8.2.0](https://github.com/tj/commander.js/releases/tag/v8.2.0) at least. And I would love to help you with that migration.

2023-08-25 13:59 UTC, joaomoreno requested changes
Please undo the whitespace changes. Also remove the huge non-user-friendly ASCII art.

2023-08-30 09:45 UTC, joaomoreno approved these changes

2023-08-30 09:46 UTC, joaomoreno approved these changes

2023-08-30 10:23 UTC, hediet approved these changes

2023-08-30 10:24 UTC, merged