Fix nodejs breaking change CVE-2024-27980
microsoft/vscode-vsce pull request #973
Opened 2024-05-02 09:36 UTC by benibenj

This pull request fixes a nodejs breaking change related to CVE-2024-27980. 

Documentation: https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

fixes #969

2024-05-02 15:46 UTC, joaomoreno requested changes

2024-05-02 15:46 UTC, joaomoreno commented on src/package.ts
> +	if ([`'`, `"`, '`', '$'].some(char => sanitizedMessage.includes(char))) {
It's impossible for this to ever return `true`, isn't it?

2024-05-02 15:46 UTC, joaomoreno commented on src/package.ts
> +	const unsafeRegex = /(?<!\\)\\(?!n)|['"`$]/g;
Why `(?<!\\)`? This feels HTML specific.

2024-05-02 15:46 UTC, joaomoreno commented on src/package.ts
> +function sanitizeCommitMessage(message?: string): string | undefined {
I feel like this function is now widely inconsistent:
- If any char of `'"`$` appears in the string, we just remove them.
- If a new line appears in the string, we throw instead.
- If the message is empty, we return `undefined` instead.

We need to make a decision: we either remove unwanted string sequences (and potentially warn the user) or we throw and stop the whole thing.

My suggestion: just remove the dangerous sequences. Easy as:

```ts
function sanitizeCommitMessage(message: string): string {
  return message.replace(/\\n|['"`$]/g, '');
}
```

2024-05-02 16:01 UTC, benibenj commented on src/package.ts
> +	const unsafeRegex = /(?<!\\)\\(?!n)|['"`$]/g;
This is part of the regex expression. It uses lookaheads and lookbehinds to make sure we allow `\n` but no other case with `\`

2024-05-02 16:16 UTC, benibenj commented on src/package.ts
> +function sanitizeCommitMessage(message?: string): string | undefined {
I think you might have miss understood some of the code. 

1. We first remove all dangerous characters. 
  Dangerous characters are:
  - ' " `
  - $
  - \ (except if it is followed by an `n`, this is the case when commit messages get long and we still want to allow them)
2. We then double check that all dangerous characters have been removed and throw if any are still present. This should hopefully never throw an error, but it makes sure that a potential attacker does not trick the replace function into keeping/creating one of the characters. These symbols are all just one character in length so probably it is actually impossible to trick the replace function.

2024-05-02 17:41 UTC, joaomoreno commented on src/package.ts
> +	const unsafeRegex = /(?<!\\)\\(?!n)|['"`$]/g;
Oh wow negative look-behinds, this is outside my expertise ✨

2024-05-02 18:51 UTC, joaomoreno approved these changes

2024-05-02 18:51 UTC, joaomoreno commented on src/package.ts
> +	return `"${sanitizedMessage}"`;
Make sure that explicit quotes are *really* necessary when using `shell: true`, since I didn't find any reference to that in the docs.

2024-05-03 07:53 UTC, benibenj commented on src/package.ts
> +	return `"${sanitizedMessage}"`;
With `shell: false` the arguments are passed directly to the executable as an array compared to `shell; true` for which they are pasted into the shell. To make sure that strings with spaces in them are considered as a single argument, quotes have to be added.

2024-05-03 07:53 UTC, merged